pygments: true
# markdown: rdiscount
markdown: kramdown
future: false
sass:
    style: compressed
 
gems:           ['jekyll-paginate', 'jekyll-multiple-languages']

languages:          ['it']
language_default:   'it'
